name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
      DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    - name: Log in to Docker Hub
      run: |
        echo "Logging in to Docker Hub"
        echo $DOCKER_PASSWORD | docker login -u $DOCKER_USERNAME --password-stdin

    - name: Verify Docker Hub authentication
      run: docker info

    - name: Verify repository exists
      run: docker pull $DOCKER_USERNAME/ophelian:latest || echo "Repository does not exist yet. Proceeding to build and push."

    - name: Run build and push script
      run: |
        chmod +x ./build-push.sh
        ./build-push.sh "ophelian" "0.1.3" "$DOCKER_USERNAME"
