name: Publish to PyPI
on:
  push:
    branches:
      - feature/add_ml_class

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          test: true

  publish:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Install twine
          run: pip install twine
            - name: Publish to PyPI
              run: |
                twine upload --username __token__ --password ${{ secrets.PYPI_TOKEN }} dist/*