name: Python package

on:
  push:
    branches: [ feature/add_ml_class ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.9

    - name: Install dependencies
      run: |
        python -m venv venv
        venv/bin/pip install --upgrade pip
        venv/bin/pip install -r requirements.txt

    - name: Linting
      run: venv/bin/pylint mymodule

    - name: Test with tox
      run: venv/bin/tox

    - name: Build and Publish
      run: |
        venv/bin/pip install --upgrade setuptools wheel
        venv/bin/python setup.py sdist bdist_wheel
        venv/bin/twine check dist/*
        venv/bin/twine upload dist/*

    - name: Deploy to PyPI
      if: success()
      uses: pypi-action/publish-package@v1
      with:
        distributions: sdist bdist_wheel
        repository: pypi
