name: Run Unit Tests

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.9'
    - name: Install Poetry
      run: |
        curl -sSL https://install.python-poetry.org | python3 -
        echo "$HOME/.local/bin" >> $GITHUB_PATH
    - name: Update lock file
      run: |
        poetry lock --no-update
    - name: Install dependencies
      run: |
        poetry install
    - name: Run Unit Tests
      run: |
        poetry run pytest
